# Generated by Django 3.0 on 2020-10-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_useractivitypath_usersession_usersessionpath"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="language_code",
            field=models.CharField(default="__", max_length=2),
        ),
        migrations.AddField(
            model_name="rlcsettings",
            name="language_settings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rlc_language",
                to="api.Language",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
