version: '2'

services:
    web:
        build: .
        command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
        expose:
            - 8000
        env_file:
            - ./environments/dev.env
        image: jehob/law-orga-backend

    nginx:
        build: ./nginx
        ports:
            - 80:80
            - 443:443
            - 1337:80
        depends_on:
            - web
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        image: jehob/law-orga-nginx
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


# local
#version: '3.7'
#
#services:
#    web:
#        build: .
#        command: python manage.py runserver 0.0.0.0:8000
#        volumes:
#            - ./:/usr/src/app/
#        ports:
#            - 8000:8000
#        env_file:
#            - ./environments/dev.env
