# Generated by Django 3.0 on 2020-10-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0020_encryptedrecorddocumentdeletionrequest_record"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recordtag", old_name="name", new_name="name_de",
        ),
    ]
