# Generated by Django 3.0 on 2020-10-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordmanagement", "0021_auto_20201027_1046"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordtag",
            name="name",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="recordtag",
            name="name_it",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="recordtag",
            name="name_de",
            field=models.CharField(max_length=200),
        ),
    ]
